Controllers/RecipeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data;
using System.Data.SqlClient;
using RecipeApp.Models;
using System.Diagnostics;

namespace RecipeApp.Controllers
{
    public class RecipeController : Controller
    {
        string connectionString = @"Data Source = (local)\SQLEXPRESS; Initial Catalog = MVCRecipes; Integrated Security = True";

        // GET: RecipeController
        [HttpGet]
        public ActionResult Index()
        {
            DataTable dtblRecipes = new DataTable();
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("SELECT * FROM Recipes", sqlCon);
                sqlDa.Fill(dtblRecipes);
            }

            return View(dtblRecipes);
        }

        // GET: RecipeController/Details/5
        public ActionResult Details(int id)
        {
            RecipeModel recipeModel = new RecipeModel();
            DataTable dtblRecipe = new DataTable();
            DataTable dtblIngredients = new DataTable();

            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "SELECT * from Recipes WHERE RecipeID = @RecipeID;";
                SqlDataAdapter sqlDa = new SqlDataAdapter(query, sqlCon);
                sqlDa.SelectCommand.Parameters.AddWithValue("@RecipeID", id);
                sqlDa.Fill(dtblRecipe);

                query = "SELECT * from Ingredients WHERE RecipeID = @RecipeID;";
                sqlDa = new SqlDataAdapter(query, sqlCon);
                sqlDa.SelectCommand.Parameters.AddWithValue("@RecipeID", id);
                sqlDa.Fill(dtblIngredients);
            }

            recipeModel.Ingredients = new List<IngredientModel>();
            for (int i = 0; i < dtblIngredients.Rows.Count; i++)
            {
                IngredientModel ingredientModel = new IngredientModel();
                ingredientModel.IngredientID = Convert.ToInt32(dtblIngredients.Rows[i][0].ToString());
                ingredientModel.RecipeID = Convert.ToInt32(dtblIngredients.Rows[i][1].ToString());
                ingredientModel.IngredientName = dtblIngredients.Rows[i][2].ToString();
                ingredientModel.Quantity = Convert.ToInt32(dtblIngredients.Rows[i][3].ToString());
                ingredientModel.UOM = dtblIngredients.Rows[i][4].ToString();
                recipeModel.Ingredients.Add(ingredientModel);

            }

            if (dtblRecipe.Rows.Count == 1)
            {
                recipeModel.RecipeID = Convert.ToInt32(dtblRecipe.Rows[0][0].ToString());
                recipeModel.RecipeName = dtblRecipe.Rows[0][1].ToString();
                recipeModel.RecipeInstructions = dtblRecipe.Rows[0][2].ToString();
                return View(recipeModel);
            }
            else
                return RedirectToAction("Index");
        }

        // GET: RecipeController/Create
        public ActionResult Create()
        {
            return View(new RecipeModel());
        }

        // POST: RecipeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RecipeModel recipeModel)
        {
            int returnValue = -1;
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "INSERT INTO Recipes VALUES(@RecipeName, @RecipeInstructions); SELECT SCOPE_IDENTITY();";
                SqlCommand sqlCmd = new SqlCommand(query, sqlCon);
                sqlCmd.Parameters.AddWithValue("@RecipeName", recipeModel.RecipeName);
                sqlCmd.Parameters.AddWithValue("@RecipeInstructions", recipeModel.RecipeInstructions);
                object returnObj = sqlCmd.ExecuteScalar();

                if (returnObj != null)
                {
                    int.TryParse(returnObj.ToString(), out returnValue);
                }

                query = "INSERT INTO Ingredients VALUES(@RecipeID, @IngredientName, @Quantity, @UOM);";
                foreach (IngredientModel ingredient in recipeModel.Ingredients)
                {
                    sqlCmd = new SqlCommand(query, sqlCon);
                    sqlCmd.Parameters.AddWithValue("@RecipeID", returnValue);
                    sqlCmd.Parameters.AddWithValue("@IngredientName", ingredient.IngredientName);
                    sqlCmd.Parameters.AddWithValue("@Quantity", ingredient.Quantity);
                    sqlCmd.Parameters.AddWithValue("@UOM", ingredient.UOM);
                    sqlCmd.ExecuteNonQuery();
                }
                

            }
            return RedirectToAction(nameof(Index));
        }

        // GET: RecipeController/Edit/5
        public ActionResult Edit(int id)
        {
            RecipeModel recipeModel = new RecipeModel();
            DataTable dtblRecipe = new DataTable();
            DataTable dtblIngredients = new DataTable();

            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "SELECT * from Recipes WHERE RecipeID = @RecipeID;";
                SqlDataAdapter sqlDa = new SqlDataAdapter(query, sqlCon);
                sqlDa.SelectCommand.Parameters.AddWithValue("@RecipeID", id);
                sqlDa.Fill(dtblRecipe);

                query = "SELECT * from Ingredients WHERE RecipeID = @RecipeID;";
                sqlDa = new SqlDataAdapter(query, sqlCon);
                sqlDa.SelectCommand.Parameters.AddWithValue("@RecipeID", id);
                sqlDa.Fill(dtblIngredients);
            }

            recipeModel.Ingredients = new List<IngredientModel>();
            for (int i = 0; i < dtblIngredients.Rows.Count; i++) 
            {
                IngredientModel ingredientModel = new IngredientModel();
                ingredientModel.IngredientID = Convert.ToInt32(dtblIngredients.Rows[i][0].ToString());
                ingredientModel.RecipeID = Convert.ToInt32(dtblIngredients.Rows[i][1].ToString());
                ingredientModel.IngredientName = dtblIngredients.Rows[i][2].ToString();
                ingredientModel.Quantity = Convert.ToInt32(dtblIngredients.Rows[i][3].ToString());
                ingredientModel.UOM = dtblIngredients.Rows[i][4].ToString();
                recipeModel.Ingredients.Add(ingredientModel);

            }

            if (dtblRecipe.Rows.Count == 1)
            {
                recipeModel.RecipeID = Convert.ToInt32(dtblRecipe.Rows[0][0].ToString());
                recipeModel.RecipeName = dtblRecipe.Rows[0][1].ToString();
                recipeModel.RecipeInstructions = dtblRecipe.Rows[0][2].ToString();
                return View(recipeModel);
            }
            else
                return RedirectToAction("Index");
        }

        // POST: RecipeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RecipeModel recipeModel)
        {

            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "UPDATE Recipes SET RecipeName = @RecipeName, RecipeInstructions = @RecipeInstructions WHERE RecipeID = @RecipeID;";
                SqlCommand sqlCmd = new SqlCommand(query, sqlCon);
                sqlCmd.Parameters.AddWithValue("@RecipeID", recipeModel.RecipeID);
                sqlCmd.Parameters.AddWithValue("@RecipeName", recipeModel.RecipeName);
                sqlCmd.Parameters.AddWithValue("@RecipeInstructions", recipeModel.RecipeInstructions);
                sqlCmd.ExecuteNonQuery();


                foreach (IngredientModel ingredient in recipeModel.Ingredients)
                {
                    if (ingredient.IngredientID > -1)
                    {
                        query = "UPDATE Ingredients SET IngredientName = @IngredientName, Quantity = @Quantity, UOM = @UOM Where IngredientID = @IngredientID;";
                        sqlCmd = new SqlCommand(query, sqlCon);
                        sqlCmd.Parameters.AddWithValue("@IngredientID", ingredient.IngredientID);
                    }
                    else
                    {
                        query = "INSERT INTO Ingredients VALUES(@RecipeID, @IngredientName, @Quantity, @UOM);";
                        sqlCmd = new SqlCommand(query, sqlCon);
                        sqlCmd.Parameters.AddWithValue("@RecipeID", recipeModel.RecipeID);
                    }

                    sqlCmd.Parameters.AddWithValue("@IngredientName", ingredient.IngredientName);
                    sqlCmd.Parameters.AddWithValue("@Quantity", ingredient.Quantity);
                    sqlCmd.Parameters.AddWithValue("@UOM", ingredient.UOM);
                    sqlCmd.ExecuteNonQuery();
                }
            }

            return RedirectToAction("Index");
        }

        // GET: RecipeController/Delete/5
        public ActionResult Delete(int id)
        {
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "DELETE FROM Recipes Where RecipeID = @RecipeID; DELETE FROM Ingredients Where RecipeID = @RecipeID;";
                SqlCommand sqlCmd = new SqlCommand(query, sqlCon);
                sqlCmd.Parameters.AddWithValue("@RecipeID", id);
                sqlCmd.ExecuteNonQuery();
            }
                return RedirectToAction("Index");
        }

    }
}

Views/Recipe/Create.cshtml
@model RecipeApp.Models.RecipeModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Recipe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" id="create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RecipeName" class="control-label"></label>
                <input asp-for="RecipeName" class="form-control" />
                <span asp-validation-for="RecipeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipeInstructions" class="control-label"></label>

                <textarea asp-for="RecipeInstructions" class="form-control" form="create" rows="10"></textarea>
                <span asp-validation-for="RecipeInstructions" class="text-danger"></span>
            </div>
            <table id="ingredientTable" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Ingredient Name</th>
                        <th>Quantity</th>
                        <th>Units</th>
                    </tr>
                </thead>
                <tbody id="ingredientTableBody">
                    <tr>
                        <td>
                            <input asp-for="@Model.Ingredients[0].IngredientName">
                            <span asp-validation-for="@Model.Ingredients[0].IngredientName" class="text-danger"></span>
                        </td>
                        <td>
                            <input asp-for="@Model.Ingredients[0].Quantity">
                            <span asp-validation-for="@Model.Ingredients[0].Quantity" class="text-danger"></span>
                        </td>
                        <td>
                            <input asp-for="@Model.Ingredients[0].UOM">
                            <span asp-validation-for="@Model.Ingredients[0].UOM" class="text-danger"></span>
                        </td>
                    </tr>
                </tbody>
            </table>
            <button type="button" class="btn btn-default" onclick="Add()">Add another ingredient</button>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script type="text/javascript">
    let ingredientCount = 1;
    let tableBody = document.getElementById("ingredientTableBody");

    function Add() {
        let newRow = tableBody.insertRow();
        let newCell1 = newRow.insertCell();
        let input1 = document.createElement("input");
        input1.setAttribute("name", "Ingredients[" + ingredientCount + "].IngredientName");
        input1.required = true;
        newCell1.appendChild(input1);
        let newCell2 = newRow.insertCell();
        let input2 = document.createElement("input");
        input2.setAttribute("name", "Ingredients[" + ingredientCount + "].Quantity");
        input2.required = true;
        newCell2.appendChild(input2);
        let newCell3 = newRow.insertCell();
        let input3 = document.createElement("input");
        input3.setAttribute("name", "Ingredients[" + ingredientCount + "].UOM");
        input3.required = true;
        newCell3.appendChild(input3);
    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Recipe/Details.cshtml
@model RecipeApp.Models.RecipeModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RecipeID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RecipeID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RecipeName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RecipeName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RecipeInstructions)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RecipeInstructions)
        </dd>
    </dl>
</div>

<table id="ingredientTable" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Ingredient Name</th>
            <th>Quantity</th>
            <th>Units</th>
        </tr>
    </thead>
    <tbody id="ingredientTableBody">
        @for (int i = 0; i < Model.Ingredients.Count; i++)
        {
            <tr>
                <td>@Model.Ingredients[i].IngredientName</td>
                <td>@Model.Ingredients[i].Quantity</td>
                <td>@Model.Ingredients[i].UOM</td>
            </tr>
        }

    </tbody>
</table>
<br />
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RecipeID }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Recipe/Edit.cshtml
@model RecipeApp.Models.RecipeModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Recipe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" id="edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="RecipeID" class="form-control" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="RecipeName" class="control-label"></label>
                <input asp-for="RecipeName" class="form-control" />
                <span asp-validation-for="RecipeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RecipeInstructions" class="control-label"></label>
                <textarea asp-for="RecipeInstructions" class="form-control" form="edit" rows="10"></textarea>
                <span asp-validation-for="RecipeInstructions" class="text-danger"></span>
            </div>
            <table id="ingredientTable" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Ingredient Name</th>
                        <th>Quantity</th>
                        <th>Units</th>
                    </tr>
                </thead>
                <tbody id="ingredientTableBody">
                    @for (int i = 0; i < Model.Ingredients.Count; i++)
                    {
                        <tr>
                            <td>
                                <input asp-for="@Model.Ingredients[i].IngredientName">
                                <span asp-validation-for="@Model.Ingredients[i].IngredientName" class="text-danger"></span>
                            </td>
                            <td>
                                <input asp-for="@Model.Ingredients[i].Quantity">
                                <span asp-validation-for="@Model.Ingredients[i].Quantity" class="text-danger"></span>
                            </td>
                            <td>
                                <input asp-for="@Model.Ingredients[i].UOM">
                                <span asp-validation-for="@Model.Ingredients[i].UOM" class="text-danger"></span>
                                <input asp-for="@Model.Ingredients[i].IngredientID" type="hidden" />
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
            <button type="button" class="btn btn-default" onclick="Add()">Add another ingredient</button>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script type="text/javascript">
    let tableBody = document.getElementById("ingredientTableBody");
    let ingredientCount = tableBody.rows.length;

    function Add() {
        let newRow = tableBody.insertRow();

        let newCell1 = newRow.insertCell();
        let input1 = document.createElement("input");
        input1.setAttribute("name", "Ingredients[" + ingredientCount + "].IngredientName");
        input1.required = true;
        newCell1.appendChild(input1);
        let newCell2 = newRow.insertCell();
        let input2 = document.createElement("input");
        input2.setAttribute("name", "Ingredients[" + ingredientCount + "].Quantity");
        input2.required = true;
        newCell2.appendChild(input2);
        let newCell3 = newRow.insertCell();
        let input3 = document.createElement("input");
        input3.setAttribute("name", "Ingredients[" + ingredientCount + "].UOM");
        input3.required = true;
        newCell3.appendChild(input3);
        let input4 = document.createElement("input");
        input4.setAttribute("name", "Ingredients[" + ingredientCount + "].IngredientID");
        input4.setAttribute("type", "hidden");
        input4.setAttribute("value", -1);
        newCell3.appendChild(input4);
        ingredientCount++;
    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Recipe/Index.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "Index";
}


<table class="table table-bordered table-striped">
    <tr>
        <th>Recipe Name</th>
        <th>Actions</th>
    </tr>
    @for (int i = 0; i < Model.Rows.Count; i++)
    {
        <tr>
            <td><a href='@Url.Action("Details", "Recipe", new {@id=@Model.Rows[i][0]})'>@Model.Rows[i][1]</a></td>
            <td>
                <a class="btn btn-default" href='@Url.Action("Edit", "Recipe", new {@id=@Model.Rows[i][0]})'>Edit</a>
                <a class="btn btn-default" href='@Url.Action("Delete", "Recipe", new {@id=@Model.Rows[i][0]})'>Delete</a>
            </td>
        </tr>
    }

</table>
<br />
<a class="btn btn-default" href='@Url.Action("Create", "Recipe", new {})'>Create</a>